### ISSUE TITLE
[V5] GPU conversion errors - RESOLVED

### ISSUE THREAD

**Issue by cyatarow** [Anjok07/ultimatevocalremovergui#149]
**Describe the bug**
In V4, GPU conversion worked fine with any of main models.
However, in V5, it no longer works and outputs some errors.

1. "CUDA out of memory" (When HP2_3BAND_44100_MSB2 is selected)
2. "Cannot load filter definition for sinc_medium" (When HP2_4BAND_44100_1, HP2_4BAND_44100_2, HP_4BAND_44100_A, HP_Vocal_4BAND_44100 or HP_Vocal_AGG_4BAND_44100 is selected)
3. "Cannot load filter definition for sinc_fastest" (When something other than the above is selected)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2 (19044.1620)
 - CPU: AMD Ryzen 5 2600
 - RAM: DDR4-2400 24GB
 - GPU: GeForce GT 1030

**The error massages**
1.

> ---------------------------
> Untracked Error
> ---------------------------
> Traceback Error: "  File "C:\Users\a1\AppsForSSD\UVR-V5GUI\inference_v5.py", line 362, in main
>     model, {'value': args.aggressiveness,'split_bin': mp.param['band'][1]['crop_stop']})
>   File "C:\Users\a1\AppsForSSD\UVR-V5GUI\inference_v5.py", line 138, in inference
>     device, model, aggressiveness)
>   File "C:\Users\a1\AppsForSSD\UVR-V5GUI\inference_v5.py", line 108, in _execute
>     pred = model.predict(X_mag_window, aggressiveness)
>   File "C:\Users\a1\AppsForSSD\UVR-V5GUI\lib_v5\nets_537238KB.py", line 107, in predict
>     h = self.forward(x_mag, aggressiveness)
>   File "C:\Users\a1\AppsForSSD\UVR-V5GUI\lib_v5\nets_537238KB.py", line 79, in forward
>     h = self.stg3_full_band_net(self.stg3_bridge(h))
>   File "C:\Users\a1\AppsForSSD\UVR-V5GUI\lib_v5\nets_537238KB.py", line 35, in __call__
>     h = self.dec2(h, e2)
>   File "C:\Users\a1\AppsForSSD\UVR-V5GUI\lib_v5\layers_537238KB.py", line 78, in __call__
>     x = torch.cat([x, skip], dim=1)
> "
> RuntimeError: "CUDA out of memory. Tried to allocate 240.00 MiB (GPU 0; 2.00 GiB total capacity; 1.40 GiB already allocated; 0 bytes free; 1.59 GiB reserved in total by PyTorch)"
> File: (Any audio file)
> Please contact the creator and attach a screenshot of this error with the file and settings that caused it!

2.

> ---------------------------
> Untracked Error
> ---------------------------
> Traceback Error: "  File "C:\Users\a1\AppsForSSD\UVR-V5GUI\inference_v5.py", line 329, in main
>     music_file, bp['sr'], False, dtype=np.float32, res_type=bp['res_type'])
>   File "C:\Users\a1\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 171, in load
>     y = resample(y, sr_native, sr, res_type=res_type)
>   File "C:\Users\a1\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 547, in resample
>     y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
>   File "C:\Users\a1\AppData\Local\Programs\Python\Python37\lib\site-packages\resampy\core.py", line 109, in resample
>     interp_win, precision, _ = get_filter(filter, **kwargs)
>   File "C:\Users\a1\AppData\Local\Programs\Python\Python37\lib\site-packages\resampy\filters.py", line 167, in get_filter
>     '{}'.format(name_or_function))
> "
> NotImplementedError: "Cannot load filter definition for sinc_medium"
> File: (Any audio file)
> Please contact the creator and attach a screenshot of this error with the file and settings that caused it!

3.

> ---------------------------
> Untracked Error
> ---------------------------
> Traceback Error: "  File "C:\Users\a1\AppsForSSD\UVR-V5GUI\inference_v5.py", line 386, in main
>     wav_instrument = spec_utils.cmb_spectrogram_to_wave(y_spec_m, mp, input_high_end_h, input_high_end_)
>   File "C:\Users\a1\AppsForSSD\UVR-V5GUI\lib_v5\spec_utils.py", line 315, in cmb_spectrogram_to_wave
>     wave = librosa.resample(wave2, bp['sr'], sr, res_type="sinc_fastest")
>   File "C:\Users\a1\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 547, in resample
>     y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
>   File "C:\Users\a1\AppData\Local\Programs\Python\Python37\lib\site-packages\resampy\core.py", line 109, in resample
>     interp_win, precision, _ = get_filter(filter, **kwargs)
>   File "C:\Users\a1\AppData\Local\Programs\Python\Python37\lib\site-packages\resampy\filters.py", line 167, in get_filter
>     '{}'.format(name_or_function))
> "
> NotImplementedError: "Cannot load filter definition for sinc_fastest"
> File: (Any audio file)
> Please contact the creator and attach a screenshot of this error with the file and settings that caused it!

**Comment by Anjok07** [comment]
This bug has been resolved. 

Please run the new run the updated requirements.txt file - https://github.com/Anjok07/ultimatevocalremovergui/blob/master/requirements.txt

**Comment by cyatarow** [comment]
I have confirmed that the errors "Cannot load filter definition for sinc_medium" and "Cannot load filter definition for sinc_fastest" have been resolved. Thank you.
However, when I select HP2 models, I still get "CUDA out of memory".
What should I do?
