### ISSUE TITLE
[Feature Request] Split mixed vocals

### ISSUE THREAD

**Issue by IndustrialOne** [Anjok07/ultimatevocalremovergui#1993]
I would like to request a feature to split for example lead vocals from background vocals.

**Comment by deton24** [comment]
See the latest Karaoke and BGV models here:
https://docs.google.com/document/d/17fjNvJzj8ZGSer7c7OFe_CNfUKbAxEh_OBv94ZdRG5c/edit?tab=t.0#heading=h.vg1wnx1dc4g0
Make sure you have the latest UVR patches with Roformer arch support
https://docs.google.com/document/d/17fjNvJzj8ZGSer7c7OFe_CNfUKbAxEh_OBv94ZdRG5c/edit?tab=t.0#heading=h.eopfi619c6zr

**Comment by IndustrialOne** [comment]
> See the latest Karaoke and BGV models here: https://docs.google.com/document/d/17fjNvJzj8ZGSer7c7OFe_CNfUKbAxEh_OBv94ZdRG5c/edit?tab=t.0#heading=h.vg1wnx1dc4g0 Make sure you have the latest UVR patches with Roformer arch support https://docs.google.com/document/d/17fjNvJzj8ZGSer7c7OFe_CNfUKbAxEh_OBv94ZdRG5c/edit?tab=t.0#heading=h.eopfi619c6zr

Thanks, but I get the following error when I try to use the newly installed Karaoke BS Roformer model:

Last Error Received:

Process: MDX-Net

If this error persists, please contact the developers with the error details.

Raw Error Details:

TypeError: "__init__() got an unexpected keyword argument 'mlp_expansion_factor'"
Traceback Error: "
  File "UVR.py", line 9217, in process_start
  File "separate.py", line 681, in seperate
  File "separate.py", line 870, in demix
  File "<@beartype(lib_v5.roformer.bs_roformer_new.BSRoformer.__init__) at 0x56395d30>", line 97, in __init__
"

Error Time Stamp [2025-10-20 10:12:08]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 5
window_size: 512
mdx_segment_size: Default
batch_size: Default
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.25
overlap_mdx: Default
overlap_mdx23: 2
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_chunk_mdxnet: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
is_mdx23_combine_stems: True
demucs_voc_inst_secondary_model: No Model Selected
demucs_other_secondary_model: No Model Selected
demucs_bass_secondary_model: No Model Selected
demucs_drums_secondary_model: No Model Selected
demucs_is_secondary_model_activate: False
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: karaoke_bs_roformer_anvuew.ckpt
chunks: Auto
margin: 44100
compensate: Auto
denoise_option: None
is_match_frequency_pitch: True
phase_option: Automatic
phase_shifts: None
is_save_align: False
is_match_silence: True
is_spec_match: False
is_mdx_c_seg_def: True
is_use_torch_inference_mode: False
is_invert_spec: False
is_deverb_vocals: False
deverb_vocal_opt: Main Vocals Only
voc_split_save_opt: Lead Only
is_mixer_mode: False
mdx_batch_size: Default
mdx_voc_inst_secondary_model: No Model Selected
mdx_other_secondary_model: No Model Selected
mdx_bass_secondary_model: No Model Selected
mdx_drums_secondary_model: No Model Selected
mdx_is_secondary_model_activate: False
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: False
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_time_correction: True
is_gpu_conversion: False
is_primary_stem_only: True
is_secondary_stem_only: False
is_testing_audio: False
is_auto_update_model_params: True
is_add_model_name: False
is_accept_any_input: False
is_save_to_input_path: False
apollo_overlap: 2
apollo_chunk_size: 5
apollo_model: Choose Model
is_task_complete: False
is_normalization: False
is_use_directml: False
is_wav_ensemble: False
is_create_model_folder: False
mp3_bit_set: 320k
semitone_shift: 0
save_format: WAV
wav_type_set: PCM_16
device_set: Default
help_hints_var: True
set_vocal_splitter: No Model Selected
is_set_vocal_splitter: False
is_save_inst_set_vocal_splitter: False
model_sample_mode: False
model_sample_mode_duration: 30
demucs_stems: All Stems
mdx_stems: All Stems
Patch Version: UVR_Patch_1_15_25_22_30_BETA

**Comment by deton24** [comment]
UVR_Patch_1_15_25_22_30_BETA is not the newest.
UVR_Patch_1_21_25_2_28_BETA is.
You need to install it over the 22_30.

Just be aware that you use the correct yank attached to the model, and that
specific model crashes with specific Torch submodule error when using RTX
5000 patch.
Your specific error was weirdly fixed in even earlier UVR patch.


pon., 20 paź 2025, 21:48 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
> UVR_Patch_1_15_25_22_30_BETA is not the newest.
> UVR_Patch_1_21_25_2_28_BETA is.
> You need to install it over the 22_30.
> 
> Just be aware that you use the correct yank attached to the model, and that
> specific model crashes with specific Torch submodule error when using RTX
> 5000 patch.
> Your specific error was weirdly fixed in even earlier UVR patch.

Shit, I neglected to install the UVR_Ptch_1_21_25_2_28_BETA_small_rofo over the main UVR Patched, forgive my stupidity. I had no excuse for not following the instructions. I have done so this time, but I still get an error. Note that I am not using the RTX 5000 patch and I am using the YAML file from the huggingface page as provided by the links you gave.

Last Error Received:

Process: MDX-Net

If this error persists, please contact the developers with the error details.

Raw Error Details:

TypeError: "__init__() got an unexpected keyword argument 'mlp_expansion_factor'"
Traceback Error: "
  File "UVR.py", line 9274, in process_start
  File "separate.py", line 730, in seperate
  File "separate.py", line 921, in demix
  File "<@beartype(lib_v5.roformer.bs_roformer_new.BSRoformer.__init__) at 0x55c3f550>", line 97, in __init__
"

Error Time Stamp [2025-10-21 10:22:03]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 5
window_size: 512
mdx_segment_size: Default
batch_size: Default
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.25
overlap_mdx: Default
overlap_mdx23: 2
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_chunk_mdxnet: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
is_mdx23_combine_stems: True
demucs_voc_inst_secondary_model: No Model Selected
demucs_other_secondary_model: No Model Selected
demucs_bass_secondary_model: No Model Selected
demucs_drums_secondary_model: No Model Selected
demucs_is_secondary_model_activate: False
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: karaoke_bs_roformer_anvuew.ckpt
chunks: Auto
margin: 44100
compensate: Auto
denoise_option: None
is_match_frequency_pitch: True
is_demud: False
phase_option: Automatic
phase_shifts: None
is_save_align: False
is_match_silence: True
is_spec_match: False
is_mdx_c_seg_def: True
is_use_torch_inference_mode: False
is_invert_spec: False
is_deverb_vocals: False
deverb_vocal_opt: Main Vocals Only
voc_split_save_opt: Lead Only
is_mixer_mode: False
mdx_batch_size: Default
mdx_voc_inst_secondary_model: No Model Selected
mdx_other_secondary_model: No Model Selected
mdx_bass_secondary_model: No Model Selected
mdx_drums_secondary_model: No Model Selected
mdx_is_secondary_model_activate: False
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: False
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_time_correction: True
is_gpu_conversion: False
is_primary_stem_only: True
is_secondary_stem_only: False
is_testing_audio: False
is_auto_update_model_params: True
is_add_model_name: False
is_accept_any_input: False
is_save_to_input_path: False
apollo_overlap: 2
apollo_chunk_size: 5
apollo_model: Choose Model
is_task_complete: False
is_normalization: False
is_use_directml: False
is_wav_ensemble: False
is_create_model_folder: False
mp3_bit_set: 320k
semitone_shift: 0
save_format: WAV
wav_type_set: PCM_16
device_set: Default
help_hints_var: True
set_vocal_splitter: No Model Selected
is_set_vocal_splitter: False
is_save_inst_set_vocal_splitter: False
model_sample_mode: False
model_sample_mode_duration: 30
demudder_method: Combine Methods
demucs_stems: All Stems
mdx_stems: All Stems
Patch Version: UVR_Patch_1_21_25_2_28_BETA

**Comment by deton24** [comment]
You could delete:
 'mlp_expansion_factor: 1' from the yaml but probably you'll get mismatch
error in result.
Nevertheless, you could try.
Still, we have some people using this model on non-RTX 5000 patch without
any issues.
You could also try out MSST on NVIDIA GPU instead. It has GUI too.
https://github.com/ZFTurbo/Music-Source-Separation-Training

wt., 21 paź 2025, 18:26 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
I don't use the RTX 5000 patch because I don't have a RTX 50xx GPU. I also tried running it on CPU only and it still returns an error.

My mpl expansion in the yaml file was 4, not 1. I tried changing it to 1 and tried removing it altogether. Got this error.

Last Error Received:

Process: MDX-Net

If this error persists, please contact the developers with the error details.

Raw Error Details:

TypeError: "__init__() got an unexpected keyword argument 'skip_connection'"
Traceback Error: "
  File "UVR.py", line 9274, in process_start
  File "separate.py", line 730, in seperate
  File "separate.py", line 921, in demix
  File "<@beartype(lib_v5.roformer.bs_roformer_new.BSRoformer.__init__) at 0x55c3e550>", line 97, in __init__
"

Error Time Stamp [2025-10-21 11:11:11]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 5
window_size: 512
mdx_segment_size: Default
batch_size: Default
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.25
overlap_mdx: Default
overlap_mdx23: 2
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_chunk_mdxnet: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
is_mdx23_combine_stems: True
demucs_voc_inst_secondary_model: No Model Selected
demucs_other_secondary_model: No Model Selected
demucs_bass_secondary_model: No Model Selected
demucs_drums_secondary_model: No Model Selected
demucs_is_secondary_model_activate: False
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: karaoke_bs_roformer_anvuew.ckpt
chunks: Auto
margin: 44100
compensate: Auto
denoise_option: None
is_match_frequency_pitch: True
is_demud: False
phase_option: Automatic
phase_shifts: None
is_save_align: False
is_match_silence: True
is_spec_match: False
is_mdx_c_seg_def: True
is_use_torch_inference_mode: False
is_invert_spec: False
is_deverb_vocals: False
deverb_vocal_opt: Main Vocals Only
voc_split_save_opt: Lead Only
is_mixer_mode: False
mdx_batch_size: Default
mdx_voc_inst_secondary_model: No Model Selected
mdx_other_secondary_model: No Model Selected
mdx_bass_secondary_model: No Model Selected
mdx_drums_secondary_model: No Model Selected
mdx_is_secondary_model_activate: False
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: False
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_time_correction: True
is_gpu_conversion: False
is_primary_stem_only: True
is_secondary_stem_only: False
is_testing_audio: False
is_auto_update_model_params: True
is_add_model_name: False
is_accept_any_input: False
is_save_to_input_path: False
apollo_overlap: 2
apollo_chunk_size: 5
apollo_model: Choose Model
is_task_complete: False
is_normalization: False
is_use_directml: False
is_wav_ensemble: False
is_create_model_folder: False
mp3_bit_set: 320k
semitone_shift: 0
save_format: WAV
wav_type_set: PCM_16
device_set: Default
help_hints_var: True
set_vocal_splitter: No Model Selected
is_set_vocal_splitter: False
is_save_inst_set_vocal_splitter: False
model_sample_mode: False
model_sample_mode_duration: 30
demudder_method: Combine Methods
demucs_stems: All Stems
mdx_stems: All Stems
Patch Version: UVR_Patch_1_21_25_2_28_BETA

**Comment by deton24** [comment]
Also, make sure you've picked BS-Roformer model type (not V2). You can
still edit it in "Edit Model Config" in the model pick menu.

wt., 21 paź 2025, 19:13 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
> Also, make sure you've picked BS-Roformer model type (not V2).

This was the problem. Everything works now, but holy shit, 5 minutes on a 13th gen CPU to process 14 seconds of audio. This model is a lot slower than the UVR-MDX-NET.

The instructions from the links you gave me appear to recommend selecting V2 unless I misinterpreted.

Also, this model successfully extracted one of the vocals, with the instrumental stem option leaving the instruments and the other vocal. What if I wanna only extract the other vocal?

**Comment by deton24** [comment]
Maybe reach the GDoc and find the vocals section and use e.g. vocfv7beta1 on that stem.

I understand that GPU Conversion is greyed out? Some newer iGPUs can be used for acceleration in UVR.

wt., 21 paź 2025, 20:07 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
No, GPU conversion works, I was just testing both. vocfv7beta1, I will try it. Thanks for all the help.

**Comment by IndustrialOne** [comment]
> Maybe reach the GDoc and find the vocals section and use e.g. vocfv7beta1 on that stem.

I've had some issues installing models that doc recommended, for example this one.

https://github.com/deton24/Lew-s-vocal-enhancer-for-Apollo-by-JusperLee/releases/tag/uni

It wouldn't accept the YAML file. I assume it's an MDX model because other ones don't accept CKPT extension, but it complains it's not compatible with MDX-Net.

**Comment by deton24** [comment]
Apollo models are located in Tools>Apollo, not in MDX-Net.

czw., 23 paź 2025, 18:42 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
> Apollo models are located in Tools>Apollo, not in MDX-Net.

DERP! I didn't know it was already included. Is there a manual or a guide for this app so I don't keep asking stupid questions? Is there a community/forum centered on this and all the various models or is it all a disorganized effort?

The doc you provided was alright but there are so many models without links or proper instructions on how to use/install them.

**Comment by deton24** [comment]
There are links to all the models in the GDoc. If it's MVSEP model without
a link, there's none available for public.

Vocal models have suggestions on some of the best already at the top, but
generally I try to keep all the best models near the top.

In most cases there's no one single good model. It can depend on a song.
Feel free to try out more than one suggested at the top.

Search for keywords in the GDoc. It should usually answer all the questions.

You can join our Discord linked on the GDoc.

You could find UVR PDF with manual I the GDoc, but it got a bit outdated
since then iirc, so better open the document outline in options and read
all the beta Roformer section and UVR FAQ later. It should have most of the
important information.


pt., 24 paź 2025, 16:05 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
No MVSEP for me.

What's the best model for separating these voices from each other?
https://vocaroo.com/19slvOumKRJf

**Comment by deton24** [comment]
There's a dedicated section in the GDoc for it.
You can even try the Becruily & Frazer Karaokes Mel Roto Model. Sometimes
it can be better than the MVSep model people suggested you here
https://discord.com/channels/708579735583588363/708595418400817162/1432296514495184967

pon., 27 paź 2025, 10:54 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
> There's a dedicated section in the GDoc for it.
> You can even try the Becruily & Frazer Karaokes Mel Roto Model.

> For two singers in a duet from one song
> (use on already separated [vocals]
> - becruily & frazer BS Karaoke (sometimes can separate even 3 singers if the vocals aren't completely glued into one, especially if it's male and female - maxerv19,

Yeah, i read that. No link to model.

**Comment by deton24** [comment]
In the Karaoke section.

pon., 27 paź 2025, 14:30 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
> In the Karaoke section.
> 
> pon., 27 paź 2025, 14:30 użytkownik IndustrialOne ***@***.***>
> napisał:
> […](#)

First one in karaoke section links to one I already tried. I tried both of these 3 days ago:
bs_roformer_karaoke_frazer_becruily.ckpt
mel_band_roformer_karaoke_becruily.ckpt

It says mel band instead of mel roto, is that the one you were referring to?

**Comment by deton24** [comment]
Yeah. The first one. The names Mel Band and Mel Roformer are sometimes used
interchangeably.

pon., 27 paź 2025, 15:30 użytkownik IndustrialOne ***@***.***>
napisał:

**Comment by IndustrialOne** [comment]
Yeah, neither worked for this sample, I guess I'll have to accept it's not feasible for now.
These karaoke models work well for separating voices when they are significantly different, like male from female voices but not if they are similar.
